DROP TABLE IF EXISTS car;

CREATE TABLE car(
  ID INT NOT NULL AUTO_INCREMENT ,
  LICENSE_PLATE VARCHAR(20) NOT NULL ,
  MANUFACTURER VARCHAR(20) NOT NULL ,
  MANUFACTURE_DATE DATE NOT NULL ,
  AGE INT NOT NULL DEFAULT 0 ,
  VERSION INT NOT NULL DEFAULT 0 ,
  UNIQUE (LICENSE_PLATE) ,
  PRIMARY KEY (ID)
);
